server.port: 8083
management.endpoints.web.exposure.include: health,auditevents,beans,caches,conditions,configprops,env,flyway,heapdump,httptrace,info,integrationgraph,jolokia,logfile,loggers,liquibase,metrics,mappings,prometheus,quartz,scheduledtasks,sessions,shutdown,startup,threaddump

spring:
  application:
    name: property-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/hellodb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true
    username: ppy_dbuser
    password: pass1234
    hikari:
      maximum-pool-size: 100
      connection-timeout: 6000
  zipkin:
    enabled: false
    baseUrl: http://zipkin:9411
  cloud:
    loadbalancer:
      ribbon:
        # to enable BlockLoadBalancer
        enabled: false
      health-check:
        initial-delay: 0
        interval: 15000 #ms
        refetch-instances-interval: 60000 #ms
        refetch-instances: true
        repeat-health-check: true
        path: #key/value (key: service name, value: uri)
          people-service: /api/1.0/about
eureka:
  client:
    enabled: false # default = true
    service-url:
      defaultZone: http://eureka:8761/eureka/

auth-service:
  jwt:
    public-key-PEM:
      -----BEGIN PUBLIC KEY-----
      MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+Ft3AzB+xBNaoBOYU0fj3+mAnrM+aYIA
      8MVZV/s28qH6mGcUfrqGnKMu7t+EVmTP0f3RGOd6sO1AnhsqkLzCrQ==
      -----END PUBLIC KEY-----

property-service:
  service-name: property-service
  api-version: 1.0
  # NEVER OVERRIDE THIS VALUE IN RUNTIME
  api-base-url: /api/1.0
  version-description: spring cloud support.
  model-mapper-location: classpath:mapper/*-Mapper.xml
  options:
    enable-debug-endpoint: true
    accept-expired-auth-token: false
    disable-permission-check: false
  role-permission-config:
    permission-map:
      ROOT_ADMIN:
      - BASIC
      - ANYTHING
      GENERAL_USER:
      - BASIC
      - PROPERTY_GET
      PROPERTY_ADMIN:
      - BASIC
      - PROPERTY_GET
      - PROPERTY_SEARCH
      - PROPERTY_ADD
      - PROPERTY_UPDATE
      - PROPERTY_DELETE
load-balancer-custom-config:
  services:
    - people-service

---
spring:
  profiles: production
  datasource:
    username: pdt_dbuser
    password: <YOUR_DB_PASSWORD>
property-service:
  options:
    enable-debug-endpoint: false
    accept-expired-auth-token: false
    disable-permission-check: false
auth-service:
  jwt:
    public-key-PEM:
      <YOUR PUBLIC KEY>
---
spring:
  profiles: enable_spring_cloud
  zipkin:
    enabled: true
eureka:
  client:
    enabled: true